const ru = {
  back: 'Назад ◀️',
  to_cart: "В корзину 🧺",
  go_to_cart: 'Перейти в корзину 🛒',
  choose_interests_you: 'Выберите то, что вас интересует.',
  contact_with_us: `<b>Для связи с нами вы можете написать или позвонить нам.</b>\nТелеграм: <i>@of_Astora</i>\nКонтакт: <i>+998(99)862-16-26</i>`,
  rate_our_work: 'оцените нашу работу от 1 🌟 до 5 🌟.',
  not_write_review: 'Вы не написали свой отзыв... <b>Напишите свой отзыв</b>',
  thanks_for_rate: 'Спасибо за ваш отзыв, оно помогает нам развиваться! Выберите действие...',
  choose_category: 'Выберите категорию...',
  empty_product: 'Тут пока пусто 😶',
  back_answer: 'Вы дошли до конца списка.',
  empty_answer: 'Вы дошли до начала списка.',
  decrease_inline: 'Минимальное кол-во 1.',
  added_product: 'Еда добавлена в корзину. Кол-во:',
  choose_product: "Выберите еду...",
  clear: 'Очистить корзину 🗑',
  order: 'Оформить заказ 🛍',
  change: 'Изменить ✍️',
  empty_cart: 'Корзина пуста 😶',
  change_actions: 'Выберите действие которое хотите совершить...',
  action_change_count: 'Изменить количество 🔢',
  action_remove_item: 'Удалить ❌',
  change_count: 'Изменеение кол-во.',
  save: 'Сохранить ✅',
  count_change_success: "Количество успешно изменено!",
  delete_items: "Удаление товара из корзины 🗑",
  deleted_message: "Товар успешно удален из корзины! ✅"
}

const uz = {
  back: 'Orqaga ◀️',
  to_cart: "Qo'shish 🧺",
  go_to_cart: "Savatga o'ting 🛒",
  choose_interests_you: "Sizni qiziqtirgan narsani tanlang.",
  contact_with_us: "<b>Biz bilan bog'lanish uchun bizga qo'ng'iroq qilishingiz yoki yozishingiz mumkin.</b>\nTelegram: <i>@of_Astora</i>\nBog'lanish: <i>+998(99)862-16-26</i>",
  rate_our_work: "ishimizga 1🌟 dan 5 🌟 gacha baho bering.",
  not_write_review: "Siz sharhingizni yozmadingiz... <b>Sharhingizni yozing</b>>",
  thanks_for_rate: "Fikr-mulohazangiz uchun tashakkur, bu bizning rivojlanishimizga yordam beradi! Amal tanlang...",
  choose_category: "Turkum tanlang...",
  empty_product: 'Bu yer bo‘sh 😶',
  back_answer: 'Siz nutqning oxiriga yetdingiz.',
  empty_answer: 'Siz roʻyxatning yuqori qismiga yetib keldingiz.',
  decrease_inline: 'Minimal miqdor 1.',
  added_product: "Ovqat savatga qo'shildi. Miqdor:",
  choose_product: "Ovqatni tanlang...",
  clear: "Savatni bo'shatish 🗑",
  change: "O'zgartirish ✍️",
  order: 'Buyurtma berish 🛍',
  empty_cart: "Savatcha bo‘sh 😶",
  change_actions: "Amal qilmoqchi bo'lgan amalni tanlang...",
  action_change_count: "Miqdorni o'zgartirish 🔢",
  action_remove_item: 'Oʻchirish ❌',
  change_count: "Miqdorini o'zgartiring.",
  save: 'Saqlash ✅',
  count_change_success: "Miqdor muvaffaqiyatli o'zgartirildi!",
  delete_items: "Buyumni savatdan olib tashlash 🗑",
  deleted_message: "Mahsulot savatdan muvaffaqiyatli olib ochirildi! ✅"
}


module.exports = { ru, uz }